f = open(r'E:\APP\android\app\src\main\java\com\dcsf\bms\MainActivity.kt', 'r', encoding='utf-8')
lines = f.readlines()
f.close()

# Replace lines 330-339 (0-indexed 329-338)
new_lines = lines[:329]
new_lines.append('            if (mfgId == 0x7030) {\n')
new_lines.append('                val dataLen = len - 3\n')
new_lines.append('                if (dataLen >= 5) {\n')
new_lines.append('                    val off = i + 4\n')
new_lines.append('                    val soc = bytes[off].toInt() and 0xFF\n')
new_lines.append('                    val voltage = ((bytes[off + 2].toInt() and 0xFF) shl 8) or (bytes[off + 1].toInt() and 0xFF)\n')
new_lines.append('                    val current = if (dataLen >= 7) ((bytes[off + 4].toInt() and 0xFF) shl 8) or (bytes[off + 3].toInt() and 0xFF) else 0\n')
new_lines.append('                    val safety = if (dataLen >= 9) ((bytes[off + 6].toInt() and 0xFF) shl 8) or (bytes[off + 5].toInt() and 0xFF) else 0\n')
new_lines.append('                    LogCollector.log("BLE", "Parsed: soc=%d V=%d I=%d safety=%d".format(soc, voltage, current, safety))\n')
new_lines.append('                    return intArrayOf(soc, voltage, current, safety)\n')
new_lines.append('                }\n')
new_lines.append('            }\n')
new_lines.extend(lines[339:])

f = open(r'E:\APP\android\app\src\main\java\com\dcsf\bms\MainActivity.kt', 'w', encoding='utf-8')
f.writelines(new_lines)
f.close()
print('DONE')
